services:
  client:
    image: beertaste-v2:latest
    ports:
      - "3005:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    # Tu w przyszłości dodasz volumes, np. dla zdjęć
    # volumes:
    #   - ./uploads:/app/public/uploads
    