services:
  client:
    image: beertaste-v2:latest
    container_name: beertaste-v2-client-1
    ports:
      - "3005:3000"
    env_file: .env
    networks:
      - supabase_default # Łączymy z Twoją siecią Supabase
    restart: always

networks:
  supabase_default:
    external: true # Informujemy, że sieć już istnieje na serwerze
    